#######################################################################

       Welcome to The CentOS and RedHat Linux Installer
                VNTECHSOLUTIONS LIMITED

Enter number of the Linux distribution you wish to install:

1. Install CentOS 9
2. Install RedHat Enterprise 9


[F1-Main] [F2-General] [F3-Expert] [F4-Kernel] [F5-Rescue]

#######################################################################

